const CalendarEvent = require('../models/CalendarEvent');
const Reminder = require('../models/Reminder');
const AutoReminderSettings = require('../models/AutoReminderSettings');
const episodeService = require('../services/episodeService');

// ----- Calendar Events -----

exports.getEvents = async (req, res) => {
  try {
    const { from, to } = req.query;
    const query = { userId: req.user._id };

    if (from || to) {
      query.startDate = {};
      if (from) query.startDate.$gte = new Date(from);
      if (to) query.startDate.$lte = new Date(to);
    }

    const events = await CalendarEvent.find(query).sort({ startDate: 1 });
    res.json(events);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.getEvent = async (req, res) => {
  try {
    const event = await CalendarEvent.findOne({
      _id: req.params.id,
      userId: req.user._id,
    });

    if (!event) {
      return res.status(404).json({ error: 'Event not found' });
    }

    res.json(event);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.createEvent = async (req, res) => {
  try {
    const {
      title,
      description,
      eventType,
      tmdbId,
      mediaType,
      seasonNumber,
      episodeNumber,
      episodeId,
      startDate,
      endDate,
      isRecurring,
      recurrencePattern,
      location,
      attendees,
      reminderMinutes,
      isAutoGenerated,
    } = req.body;

    if (!title || !eventType || !startDate) {
      return res
        .status(400)
        .json({ error: 'title, eventType and startDate are required' });
    }

    const event = await CalendarEvent.create({
      userId: req.user._id,
      title,
      description,
      eventType,
      tmdbId,
      mediaType,
      seasonNumber,
      episodeNumber,
      episodeId,
      startDate,
      endDate,
      isRecurring: !!isRecurring,
      recurrencePattern: recurrencePattern || null,
      location,
      attendees: attendees || [],
      reminderMinutes: typeof reminderMinutes === 'number' ? reminderMinutes : null,
      isAutoGenerated: isAutoGenerated || false,
    });

    res.status(201).json(event);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.updateEvent = async (req, res) => {
  try {
    const update = { ...req.body, updatedAt: new Date() };

    const event = await CalendarEvent.findOneAndUpdate(
      { _id: req.params.id, userId: req.user._id },
      update,
      { new: true, runValidators: true },
    );

    if (!event) {
      return res.status(404).json({ error: 'Event not found' });
    }

    res.json(event);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.deleteEvent = async (req, res) => {
  try {
    const event = await CalendarEvent.findOneAndDelete({
      _id: req.params.id,
      userId: req.user._id,
    });

    if (!event) {
      return res.status(404).json({ error: 'Event not found' });
    }

    // Optionally delete associated reminders
    await Reminder.deleteMany({ calendarEventId: event._id });

    res.json({ message: 'Event deleted successfully' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// ----- Reminders -----

exports.getReminders = async (req, res) => {
  try {
    const { from, to, isSent } = req.query;
    const query = { userId: req.user._id };

    if (from || to) {
      query.reminderDate = {};
      if (from) query.reminderDate.$gte = new Date(from);
      if (to) query.reminderDate.$lte = new Date(to);
    }

    if (typeof isSent !== 'undefined') {
      query.isSent = isSent === 'true';
    }

    const reminders = await Reminder.find(query).sort({ reminderDate: 1 });
    res.json(reminders);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

exports.createReminder = async (req, res) => {
  try {
    const {
      calendarEventId,
      reminderType,
      tmdbId,
      mediaType,
      seasonNumber,
      episodeNumber,
      episodeId,
      reminderDate,
      notificationMethod,
      isAutoGenerated,
    } = req.body;

    if (!reminderType || !reminderDate) {
      return res
        .status(400)
        .json({ error: 'reminderType and reminderDate are required' });
    }

    const reminder = await Reminder.create({
      userId: req.user._id,
      calendarEventId: calendarEventId || null,
      reminderType,
      tmdbId: tmdbId || null,
      mediaType: mediaType || null,
      seasonNumber,
      episodeNumber,
      episodeId,
      reminderDate,
      notificationMethod: notificationMethod || 'in_app',
      isAutoGenerated: isAutoGenerated || false,
    });

    res.status(201).json(reminder);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// ----- Episode-Related Endpoints -----

// Get upcoming episodes from shows airing in next 7 days (public, but personalized if logged in)
exports.getUpcomingEpisodes = async (req, res) => {
  try {
    // Check if user wants to see all shows (not just tracked)
    const showAll = req.query.showAll === 'true';
    
    // If showAll is true, don't filter by user (show all shows)
    // Otherwise, if user is authenticated, show their tracked shows; if not, show all shows
    const userId = (showAll || !req.user) ? null : req.user._id;
    const episodes = await episodeService.getUpcomingEpisodesForUser(userId);
    res.json({ episodes });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Get recent episodes (public, but personalized if logged in)
exports.getRecentEpisodes = async (req, res) => {
  try {
    const days = parseInt(req.query.days) || 7;
    const userId = req.user ? req.user._id : null;
    if (!userId) return res.json({ episodes: [] });

    const episodes = await episodeService.getRecentEpisodesForUser(userId, days);
    res.json({ episodes });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Get "What's Next" list (public, but personalized if logged in)
exports.getWhatsNext = async (req, res) => {
  try {
    // If user is authenticated, show their tracked shows; otherwise return empty array
    const userId = req.user ? req.user._id : null;
    const whatsNext = await episodeService.getWhatsNextEpisodes(userId);
    res.json({ whatsNext });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Get all episodes airing in a given month (1st through last day). Public.
exports.getEpisodesForMonth = async (req, res) => {
  try {
    const year = req.query.year;
    const month = req.query.month;
    if (!year || !month) {
      return res.status(400).json({ error: 'year and month query params are required' });
    }
    const episodes = await episodeService.getEpisodesForMonth(year, month);
    res.json({ episodes });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Get next episode for a specific show
exports.getNextEpisodeForShow = async (req, res) => {
  try {
    const { tvId } = req.params;
    const nextEpisode = await episodeService.getNextEpisodeForShow(tvId);

    if (!nextEpisode) {
      return res.json({ nextEpisode: null, message: 'No upcoming episodes' });
    }

    res.json({
      nextEpisode,
      countdown: episodeService.calculateCountdown(nextEpisode.air_date),
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Enable auto-reminders for new episodes
exports.enableAutoReminders = async (req, res) => {
  try {
    const { tvId, reminderMinutes, notificationMethod } = req.body;

    if (!tvId) {
      return res.status(400).json({ error: 'tvId is required' });
    }

    const settings = await AutoReminderSettings.findOneAndUpdate(
      { userId: req.user._id, tmdbTvId: tvId },
      {
        userId: req.user._id,
        tmdbTvId: tvId,
        isEnabled: true,
        reminderMinutes: reminderMinutes || 60,
        notificationMethod: notificationMethod || 'in_app',
      },
      { upsert: true, new: true }
    );

    res.json({ settings });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};

// Disable auto-reminders for a show
exports.disableAutoReminders = async (req, res) => {
  try {
    const { tvId } = req.params;

    const settings = await AutoReminderSettings.findOneAndUpdate(
      { userId: req.user._id, tmdbTvId: parseInt(tvId) },
      { isEnabled: false },
      { new: true }
    );

    if (!settings) {
      return res.status(404).json({ error: 'Auto-reminder settings not found' });
    }

    res.json({ settings });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
};


