const mongoose = require('mongoose');

const calendarEventSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  title: {
    type: String,
    required: true,
  },
  description: {
    type: String,
    default: null,
  },
  eventType: {
    type: String,
    enum: ['movie_night', 'tv_episode', 'release_reminder', 'custom'],
    required: true,
  },
  tmdbId: {
    type: Number,
    default: null,
  },
  mediaType: {
    type: String,
    enum: ['movie', 'tv', null],
    default: null,
  },
  // For TV episodes:
  seasonNumber: {
    type: Number,
    default: null,
  },
  episodeNumber: {
    type: Number,
    default: null,
  },
  episodeId: {
    type: Number,
    default: null, // TMDb episode ID
  },
  startDate: {
    type: Date,
    required: true,
  },
  endDate: {
    type: Date,
    default: null,
  },
  isRecurring: {
    type: Boolean,
    default: false,
  },
  recurrencePattern: {
    type: Object,
    default: null,
  },
  location: {
    type: String,
    default: null,
  },
  attendees: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    },
  ],
  reminderMinutes: {
    type: Number,
    default: null,
  },
  isAutoGenerated: {
    type: Boolean,
    default: false, // True if auto-created from episode air date
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
});

calendarEventSchema.pre('save', function (next) {
  this.updatedAt = Date.now();
  next();
});

calendarEventSchema.index({ userId: 1, startDate: 1 });
calendarEventSchema.index({ tmdbId: 1, seasonNumber: 1, episodeNumber: 1 });

module.exports = mongoose.model('CalendarEvent', calendarEventSchema);


