const mongoose = require('mongoose');

const reminderSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  calendarEventId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'CalendarEvent',
    default: null,
  },
  reminderType: {
    type: String,
    enum: ['new_episode', 'release_date', 'leaving_soon', 'custom'],
    required: true,
  },
  tmdbId: {
    type: Number,
    default: null,
  },
  mediaType: {
    type: String,
    enum: ['movie', 'tv', null],
    default: null,
  },
  // For TV episodes:
  seasonNumber: {
    type: Number,
    default: null,
  },
  episodeNumber: {
    type: Number,
    default: null,
  },
  episodeId: {
    type: Number,
    default: null, // TMDb episode ID
  },
  reminderDate: {
    type: Date,
    required: true,
  },
  isSent: {
    type: Boolean,
    default: false,
  },
  notificationMethod: {
    type: String,
    enum: ['email', 'push', 'in_app'],
    default: 'in_app',
  },
  isAutoGenerated: {
    type: Boolean,
    default: false, // True if auto-created
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

reminderSchema.index({ userId: 1, reminderDate: 1, isSent: 1 });
reminderSchema.index({ reminderDate: 1, isSent: 1 });
reminderSchema.index({ tmdbId: 1, seasonNumber: 1, episodeNumber: 1 });

module.exports = mongoose.model('Reminder', reminderSchema);


